name: zIRAM Kernel Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm make linux-headers-$(uname -r)

    - name: Compile with GCC
      run: |
        make
        mv main.ko ziram_core.ko

    - name: Check Module Info
      run: modinfo ziram_core.ko

    - name: Load and Test Hijack
      run: |
        # 2. Check if kprobes are actually supported by this kernel
        if [ ! -d /sys/kernel/debug/kprobes ]; then
          echo "ERROR: Kprobes not supported on this kernel!"
          exit 1
        fi
        
        # 4. Try inserting module now
        sudo insmod ziram_core.ko

    - name: Upload zIRAM Kernel Module
      uses: actions/upload-artifact@v4
      with:
        name: ziram-ko
        path: |
          ziram_core.ko
          Module.symvers
